#!/usr/bin/env bash
# fable-token-saver — one-click external model provider setup
#
# Installs CLI wrappers that launch Claude Code against alternative
# Anthropic-compatible endpoints, so the orchestrator (Fable/Opus) can
# dispatch implementation work to cheaper external models:
#
#   claude-kimi / claude-kimi-bypass                Kimi coding endpoint
#   claude-glm  / claude-glm-bypass                 GLM main + turbo background
#   claude-glm-turbo / claude-glm-turbo-bypass      GLM turbo everywhere
#
# The -bypass variants add --dangerously-skip-permissions (required for
# headless `-p` dispatch; a headless worker cannot answer permission prompts).
#
# API keys are stored in ~/.claude/fable-token-saver/providers.env (chmod 600),
# never in this repo and never inline in your shell rc.
#
# Usage:
#   bash scripts/setup-model-providers.sh                       # interactive / auto-migrate
#   KIMI_AUTH_TOKEN=... GLM_AUTH_TOKEN=... bash scripts/setup-model-providers.sh
#
# Idempotent: safe to re-run; re-running updates wrappers and keeps existing keys.

set -euo pipefail

BASE_DIR="$HOME/.claude/fable-token-saver"
BIN_DIR="$BASE_DIR/bin"
ENV_FILE="$BASE_DIR/providers.env"
ZSHRC="$HOME/.zshrc"

KIMI_BASE_URL_DEFAULT="https://api.kimi.com/coding/"
GLM_BASE_URL_DEFAULT="https://open.bigmodel.cn/api/anthropic"
GLM_MODEL_DEFAULT="glm-5.1"
GLM_SMALL_FAST_MODEL_DEFAULT="glm-5-turbo"

mkdir -p "$BIN_DIR"

# --- 1. Collect keys: env var > existing providers.env > migrate from .zshrc > prompt ---

existing_env_val() { # existing_env_val VAR
  [ -f "$ENV_FILE" ] && sed -n "s/^$1=\"\(.*\)\"$/\1/p" "$ENV_FILE" | head -1 || true
}

KIMI_KEY="${KIMI_AUTH_TOKEN:-$(existing_env_val KIMI_AUTH_TOKEN)}"
GLM_KEY="${GLM_AUTH_TOKEN:-$(existing_env_val GLM_AUTH_TOKEN)}"

# Migrate from old-style claude-kimi()/claude-glm() functions in .zshrc, if present.
if [ -z "$KIMI_KEY" ] && [ -f "$ZSHRC" ]; then
  KIMI_KEY="$(sed -n '/^claude-kimi(/,/^}/p' "$ZSHRC" | sed -n 's/.*ANTHROPIC_AUTH_TOKEN="\([^"]*\)".*/\1/p' | head -1)"
  [ -n "$KIMI_KEY" ] && echo "· migrated Kimi key from existing claude-kimi() in ~/.zshrc"
fi
if [ -z "$GLM_KEY" ] && [ -f "$ZSHRC" ]; then
  GLM_KEY="$(sed -n '/^claude-glm(/,/^}/p' "$ZSHRC" | sed -n 's/.*ANTHROPIC_AUTH_TOKEN="\([^"]*\)".*/\1/p' | head -1)"
  [ -n "$GLM_KEY" ] && echo "· migrated GLM key from existing claude-glm() in ~/.zshrc"
fi

if [ -z "$KIMI_KEY" ] && [ -t 0 ]; then
  printf "Kimi API key (empty to skip Kimi): "
  read -r KIMI_KEY
fi
if [ -z "$GLM_KEY" ] && [ -t 0 ]; then
  printf "GLM (BigModel) API key (empty to skip GLM): "
  read -r GLM_KEY
fi

if [ -z "$KIMI_KEY" ] && [ -z "$GLM_KEY" ]; then
  echo "No keys provided — nothing to configure." >&2
  exit 1
fi

# --- 2. Write providers.env ---

umask 077
cat > "$ENV_FILE" <<EOF
# fable-token-saver external model providers
# chmod 600 — keep this file out of every repo.
KIMI_BASE_URL="${KIMI_BASE_URL:-$KIMI_BASE_URL_DEFAULT}"
KIMI_AUTH_TOKEN="$KIMI_KEY"
GLM_BASE_URL="${GLM_BASE_URL:-$GLM_BASE_URL_DEFAULT}"
GLM_AUTH_TOKEN="$GLM_KEY"
GLM_MODEL="${GLM_MODEL:-$GLM_MODEL_DEFAULT}"
GLM_SMALL_FAST_MODEL="${GLM_SMALL_FAST_MODEL:-$GLM_SMALL_FAST_MODEL_DEFAULT}"
EOF
chmod 600 "$ENV_FILE"
echo "· wrote $ENV_FILE"

# --- 3. Generate wrapper scripts ---

write_wrapper() { # write_wrapper NAME TOKEN_VAR URL_VAR MODEL SMALL_FAST_MODEL BYPASS
  local name="$1" token_var="$2" url_var="$3" model="$4" small="$5" bypass="$6"
  local flags=""
  [ "$bypass" = "yes" ] && flags=" --dangerously-skip-permissions"
  {
    echo '#!/bin/sh'
    echo "# generated by fable-token-saver scripts/setup-model-providers.sh — do not edit; re-run setup instead"
    echo "ENV_FILE=\"\$HOME/.claude/fable-token-saver/providers.env\""
    echo "[ -f \"\$ENV_FILE\" ] || { echo \"$name: missing \$ENV_FILE — re-run setup-model-providers.sh\" >&2; exit 1; }"
    echo ". \"\$ENV_FILE\""
    echo "[ -n \"\${$token_var:-}\" ] || { echo \"$name: $token_var not set in \$ENV_FILE\" >&2; exit 1; }"
    echo "unset ANTHROPIC_API_KEY ANTHROPIC_MODEL ANTHROPIC_SMALL_FAST_MODEL CLAUDECODE CLAUDE_CODE_ENTRYPOINT"
    echo "export ANTHROPIC_BASE_URL=\"\$$url_var\""
    echo "export ANTHROPIC_AUTH_TOKEN=\"\$$token_var\""
    [ -n "$model" ] && echo "export ANTHROPIC_MODEL=\"$model\""
    [ -n "$small" ] && echo "export ANTHROPIC_SMALL_FAST_MODEL=\"$small\""
    echo "exec claude$flags \"\$@\""
  } > "$BIN_DIR/$name"
  chmod 755 "$BIN_DIR/$name"
  echo "· installed $BIN_DIR/$name"
}

if [ -n "$KIMI_KEY" ]; then
  write_wrapper claude-kimi        KIMI_AUTH_TOKEN KIMI_BASE_URL "" "" no
  write_wrapper claude-kimi-bypass KIMI_AUTH_TOKEN KIMI_BASE_URL "" "" yes
fi
if [ -n "$GLM_KEY" ]; then
  write_wrapper claude-glm              GLM_AUTH_TOKEN GLM_BASE_URL "\$GLM_MODEL" "\$GLM_SMALL_FAST_MODEL" no
  write_wrapper claude-glm-bypass       GLM_AUTH_TOKEN GLM_BASE_URL "\$GLM_MODEL" "\$GLM_SMALL_FAST_MODEL" yes
  write_wrapper claude-glm-turbo        GLM_AUTH_TOKEN GLM_BASE_URL "\$GLM_SMALL_FAST_MODEL" "\$GLM_SMALL_FAST_MODEL" no
  write_wrapper claude-glm-turbo-bypass GLM_AUTH_TOKEN GLM_BASE_URL "\$GLM_SMALL_FAST_MODEL" "\$GLM_SMALL_FAST_MODEL" yes
fi

# --- 4. PATH block in ~/.zshrc ---

MARK_BEGIN="# >>> fable-token-saver providers >>>"
MARK_END="# <<< fable-token-saver providers <<<"
if ! grep -qF "$MARK_BEGIN" "$ZSHRC" 2>/dev/null; then
  {
    echo ""
    echo "$MARK_BEGIN"
    echo "export PATH=\"\$HOME/.claude/fable-token-saver/bin:\$PATH\""
    echo "$MARK_END"
  } >> "$ZSHRC"
  echo "· added PATH block to $ZSHRC"
else
  echo "· PATH block already in $ZSHRC"
fi

# --- 5. Warn about old shell functions that would shadow the new commands ---

for fn in claude-kimi claude-kimi-safe claude-glm claude-glm-safe claude-glm-turbo claude-glm-turbo-safe; do
  if grep -qE "^${fn}\(\)" "$ZSHRC" 2>/dev/null; then
    echo "⚠ $ZSHRC still defines ${fn}() — the shell function shadows the new command in interactive shells. Remove it (keys are now in providers.env)."
  fi
done

echo ""
echo "Done. Open a new shell (or: export PATH=\"\$HOME/.claude/fable-token-saver/bin:\$PATH\") and try:"
[ -n "$KIMI_KEY" ] && echo "  claude-kimi-bypass -p 'Reply with exactly: OK'"
[ -n "$GLM_KEY" ]  && echo "  claude-glm-bypass  -p 'Reply with exactly: OK'"
